server:
  port: 8084
#Eureka配置
eureka:
  instance:
    hostname: eureka02 #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向Eureka注册中心注册自己
    fetch-registry: false #如果为false则表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://eureka01:8083/eureka/,http://eureka:8082/eureka/
