server:
  port: 8083
#Eureka配置
eureka:
  instance:
    hostname: eureka01 #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向Eureka注册中心注册自己
    fetch-registry: false #如果为false则表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://eureka:8082/eureka/,http://eureka02:8084/eureka/
